```sql
INSERT INTO BADGE (BADGE_NAME, DESCRIPTION, POINTS_REQUIRED, BADGE_IMAGE, CREATE_DATE, UPDATE_DATE) VALUES ('Beginner', 'For beginners', 10, 'beginner.png', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO BADGE (BADGE_NAME, DESCRIPTION, POINTS_REQUIRED, BADGE_IMAGE, CREATE_DATE, UPDATE_DATE) VALUES ('Intermediate', 'For intermediates', 50, 'intermediate.png', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO BADGE (BADGE_NAME, DESCRIPTION, POINTS_REQUIRED, BADGE_IMAGE, CREATE_DATE, UPDATE_DATE) VALUES ('Advanced', 'For advanced users', 100, 'advanced.png', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO BADGE (BADGE_NAME, DESCRIPTION, POINTS_REQUIRED, BADGE_IMAGE, CREATE_DATE, UPDATE_DATE) VALUES ('Expert', 'For experts', 200, 'expert.png', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
-- Add 6 more INSERT statements for the remaining badges
```